Panutad Sirikul

650510714

Lab_01_01

229323 Sec 002

จงเขียนโปรแกรมสำหรับรับค่าตัวแปร array_data ซึ่งเป็นข้อมูลชนิด ndarray ที่เป็นเมตริกซ์ขนาด nxn และทำการคำนวณค่าของตัวแปรดังต่อไปนี้ โดยสามารถเลือกใช้ method หรือฟังก์ชัน built-in

In [7]:
import numpy as np
n = int(input("Enter dimension of matrix: "))

arr_data = np.random.randint(100,size=n*n)
print(arr_data)
print("---------------")
arr_data = arr_data.reshape(n,n)
print(arr_data)
print(type(arr_data))

Enter dimension of matrix: 6
[56 39 16 51 58 23 20 40 75 42 11 95 58 22 54 16 40 19  0 90 43 47 23 34
 61 20 20 44 82 36 82 74 50 61 79 94]
---------------
[[56 39 16 51 58 23]
 [20 40 75 42 11 95]
 [58 22 54 16 40 19]
 [ 0 90 43 47 23 34]
 [61 20 20 44 82 36]
 [82 74 50 61 79 94]]
<class 'numpy.ndarray'>


In [8]:
# บวกค่าข้อมูลแนวตั้งเก็บในตัวแปร sum_row
sum_row = arr_data.sum(axis=0)
print(sum_row)
sum_row = sum(sum_row)
print("Evaluate =", sum_row)

[277 285 258 261 293 301]
Evaluate = 1675


In [9]:
# บวกค่าข้อมูลแนวนอนเก็บในตัวแปร sum_col
sum_col = arr_data.sum(axis=1)
print(sum_col)
sum_col = sum(sum_col)
print("Evaluate =", sum_col)

[243 283 209 237 263 440]
Evaluate = 1675


In [10]:
# บวกค่าข้อมูลแนวทแยงมุมเก็บในตัวแปร sum_diagonal
# โดยค่าแรกคือ ผลบวกของค่าในแนวทแยงมุม จากมุมบนซ้ายไปยังล่างขวา
arr1 = np.diag(arr_data)
print(arr1)
# และค่าที่สองคือ ผลบวกของค่าในแนวทแยงมุม จากมุมบนขวาไปยังล่างซ้าย
arr2 = np.fliplr(arr_data)
arr2 = np.diag(arr2)
print(arr2)

sum_diagonal = sum(arr1) + sum(arr2)
print("Total =", sum_diagonal)

[56 40 54 47 82 94]
[23 11 16 43 20 82]
Total = 568


In [11]:
# บวกค่าข้อมูลทุกตัวเก็บในตัวแปร sum_total
sum_total = sum(sum(arr_data))
print(sum_total)

1675


In [14]:
# ทำการหาเมตริกซ์ที่เกิดจากผลรวมของเมตริกซ์ที่กำหนดให้กับเมตริกซ์ Transpose
print(arr_data)
print("---------------")

arr3 = arr_data.transpose()
print(arr3)

print("---------------\nEvaluating...\n---------------")

try:
  result = arr_data+arr3
  print(result)
except ValueError:
  print("can not add matrix")

[[56 39 16 51 58 23]
 [20 40 75 42 11 95]
 [58 22 54 16 40 19]
 [ 0 90 43 47 23 34]
 [61 20 20 44 82 36]
 [82 74 50 61 79 94]]
---------------
[[56 20 58  0 61 82]
 [39 40 22 90 20 74]
 [16 75 54 43 20 50]
 [51 42 16 47 44 61]
 [58 11 40 23 82 79]
 [23 95 19 34 36 94]]
---------------
Evaluating...
---------------
[[112  59  74  51 119 105]
 [ 59  80  97 132  31 169]
 [ 74  97 108  59  60  69]
 [ 51 132  59  94  67  95]
 [119  31  60  67 164 115]
 [105 169  69  95 115 188]]
