In [ ]:
# Panutad Sirikul
# 650510714
# Lab01_01
# 229323 Sec 001

# randn
import numpy as np
n = int(input("Enter dimension of matrix "))
arr=np.random.randn(n,n)
print(arr)
print(type(arr))

Enter dimension of matrix 4
[[-1.3225726   1.47040223 -0.15154958  0.55369559]
 [ 1.70944501  0.10802445 -2.41400612  0.82785353]
 [-0.13766249  0.81577889 -1.25279549 -2.14201607]
 [-0.23545754  0.76168275  1.13281922 -1.4108533 ]]
<class 'numpy.ndarray'>


In [ ]:
# randint ได้ list
# reshape ได้ matrix
import numpy as np
n = int(input("Enter dimension of matrix "))
arr=np.random.randint(100,size=n*n)
print(arr)
arr1=arr.reshape(n,n)
print(arr1)
print(type(arr1))

Enter dimension of matrix 4
[60 83  6 93  5  7 83 37 99 68 44 88 67  1 36 24]
[[60 83  6 93]
 [ 5  7 83 37]
 [99 68 44 88]
 [67  1 36 24]]
<class 'numpy.ndarray'>


In [ ]:
x = np.diag(arr1) # แทยง
print(x)

[60  7 44 24]


In [ ]:
arr2 = np.fliplr(arr1)
print(arr2)

[[93  6 83 60]
 [37 83  7  5]
 [88 44 68 99]
 [24 36  1 67]]


In [ ]:
y = np.diag(arr2)
print(y)

[93 83 68 67]


In [ ]:
# transpose กลับ แถวเป็นคอลัมน์
print(arr1)
arr3=arr1.transpose()
print(arr3)

[[60 83  6 93]
 [ 5  7 83 37]
 [99 68 44 88]
 [67  1 36 24]]
[[60  5 99 67]
 [83  7 68  1]
 [ 6 83 44 36]
 [93 37 88 24]]


In [ ]:
arr4=np.random.randint(20,50,size=10)
arr5=arr4.reshape(2,5)
print(arr5)
arr6=arr4.reshape(5,2)
print(arr6)
arr7=arr4.reshape(2,5)
print(arr7)

[[32 27 41 37 42]
 [30 25 22 40 34]]
[[32 27]
 [41 37]
 [42 30]
 [25 22]
 [40 34]]
[[32 27 41 37 42]
 [30 25 22 40 34]]


In [ ]:
try: # ได้เวลาดักจับ Error
  result=arr5+arr6
  print(result)
except ValueError:
  print("can not add matrix")

can not add matrix


In [ ]:
try:
  result=arr5+arr7
  print(result)
except ValueError:
  print("can not add matrix")

[[64 54 82 74 84]
 [60 50 44 80 68]]


In [ ]:
input_string = input("Enter string : ").lower().strip()
print(input_string)

Enter string : French fries
french fries


In [ ]:
# ข้อ 3
import numpy as np
a=np.array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 2., 0., 1., 0., 2., 1., 1.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 2.],
       [1., 1., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
b=np.array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [68.],
       [27.],
       [ 4.],
       [ 8.],
       [36.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [38.],
       [36.],
       [ 0.],
       [ 0.],
       [25.],
       [20.],
       [15.],
       [15.],
       [22.],
       [ 7.],
       [10.],
       [ 0.],
       [ 6.]])

In [ ]:
result, *_ = np.linalg.lstsq(a, b, rcond=None)
result

array([[ 6.],
       [ 8.],
       [ 7.],
       [ 4.],
       [15.],
       [12.],
       [10.],
       [10.],
       [ 4.],
       [10.]])

In [11]:
k= int(result[0,0])
print (k)
for i in range(k) :
  print("0",end="")

6
000000

In [ ]:
# [บวกกันได้เลย]
x = <ndarray>
y = <ndarray>
z = x + y