Panutad Sirikul

650510714

Lab_01_02

229323 Sec 002

จงเขียนโปรแกรมเพื่อทำการรับค่าเมตริกซ์ 2 ค่า ที่มีขนาดมิติคือ axb และ mxn จากนั้นทำการคำนวณค่าต่อไปนี้ (ก่อนทำการคำนวณให้ทำการตรวจสอบมิติว่าสามารถคำนวณได้หรือไม่ หากไม่สามารถคำนวณได้ ให้ทำการแสดงข้อความว่า “This calculation is wrong.”)

In [5]:
import numpy as np
a = int(input("row = "))
b = int(input("column = "))
bf1 = np.random.randint(100,size=a*b)
print("list\n", bf1)
bf1 = bf1.reshape(a,b)
print("to matrix\n", bf1)

row = 4
column = 3
list
 [ 1 57 99 71 95 43 98 24 55 66 53 44]
to matrix
 [[ 1 57 99]
 [71 95 43]
 [98 24 55]
 [66 53 44]]


In [6]:
m = int(input("row = "))
n = int(input("column = "))
bf2 = np.random.randint(100,size=m*n)
print("list\n", bf2)
bf2 = bf2.reshape(m,n)
print("to matrix\n", bf2)

row = 4
column = 3
list
 [54  4 89 52 76 18 76 65 67 57 98 39]
to matrix
 [[54  4 89]
 [52 76 18]
 [76 65 67]
 [57 98 39]]


In [7]:
# ผลบวกของเมตริกซ์ทั้งสอง
try:
  sum = bf1 + bf2
  print(sum)
except ValueError:
  print("This calculation is wrong.")

[[ 55  61 188]
 [123 171  61]
 [174  89 122]
 [123 151  83]]


In [8]:
# ผลคูณของเมตริกซ์
try:
  mul = bf1 * bf2
  print(mul)
except ValueError:
  print("This calculation is wrong.")

[[  54  228 8811]
 [3692 7220  774]
 [7448 1560 3685]
 [3762 5194 1716]]


In [9]:
# รับค่าตัวแปร k โดย k เป็นเลขจำนวนเต็มใดๆ แล้วนำไปคูณกับเมตริกซ์ตัวแรกที่รับเข้ามา
k = int(input("multiplier = "))
try:
  res = k * bf1
  print(res)
except ValueError:
  print("This calculation is wrong.")


multiplier = 3
[[  3 171 297]
 [213 285 129]
 [294  72 165]
 [198 159 132]]
