In [1]:
def lazy_range(n):
  i=0
  while i<n :
    yield i
    i+=1

lazy_evens=(i for i in lazy_range(10) if i%2==0)
print(lazy_evens)
for item in lazy_evens:
  print(item)

<generator object <genexpr> at 0x7f98ca749cb0>
0
2
4
6
8


In [ ]:
import random

random.seed(20) # เราควรใส่ seed ก่อนใช้ random.random()
for i in range(2):
  uniform_randoms = [random.random() for _ in range(4)]
  print (uniform_randoms)

[0.9056396761745207, 0.6862541570267026, 0.7665092563626442, 0.9046162378132736]
[0.2598274474889769, 0.6357258696059892, 0.9049456946664788, 0.8721303740697106]


In [ ]:
# ถ้าเราไม่ใส่ seed ตัวเลขจะเปลี่ยนทุกครั้งที่เรา Run
import random

for i in range(2):
  uniform_randoms = [random.random() for _ in range(4)]
  print (uniform_randoms)

[0.1633494468328136, 0.11769688804215006, 0.02334472736383486, 0.7057837116268251]
[0.8591126415220334, 0.21966561357625647, 0.23756936979303123, 0.012980087094521142]


In [ ]:
x = random.randrange(10)
# choose randomly from [0,1,2,...,9]
print(x)
y = random.randrange(3,6)
# choose randomly from [3,4,5]
print(y)

5
5


In [ ]:
import numpy as np
import random
a=np.arange(10)
print(a)
random.shuffle(a) # ผลลัพธ์เปลี่ยนไปเรื่อยๆ
print(a)

[0 1 2 3 4 5 6 7 8 9]
[1 6 3 7 5 0 8 2 9 4]


In [ ]:
my_friend = random.choice(["Alice", "Bob", "Tom"])
print(my_friend)
type(my_friend)

Bob


str

In [ ]:
lottery_numbers=random.sample(range(7),6) # sample can't have more than population
lottery_numbers

[0, 4, 6, 1, 3, 5]

In [ ]:
# Allow Duplication!
four_replace = [random.choice(range(10)) for _ in range(4)]
print(four_replace)

[1, 9, 1, 1]


In [ ]:
import numpy as np

arr = np.random.randn(3,2)
print(arr)
print(type(arr)) # numpy จะให้ ndarray สามารถนำไปใช้ต่อได้เช่น arr.mean()
                 # random ของ python จะให้ผลลัพธ์เป็น list ซึ่งจะใช้ต่ออาจลำบากหน่อย

[[-0.20201503 -1.12599017]
 [-1.21994613  0.74189667]
 [-0.70066972 -0.19032259]]
<class 'numpy.ndarray'>


In [ ]:
arr=np.array([[2.1695,-0.1149,2.0037,0.0296],
       [0.7953,0.1181,-0.7485,0.585],
       [0.1527,-1.5657,-0.5625,-0.0327],
       [-0.929,-0.4826,-0.0363,1.0954],
       [0.9889,-0.5895,1.5817,-0.5287]])
print(type(arr))
print(arr.mean(axis=1)) # axis=1 คือ หาตามแนวแถว
print(arr.sum(axis=0)) # axis=0 คือ หาตามแนวคอลัมน์

<class 'numpy.ndarray'>
[ 1.021975  0.187475 -0.50205  -0.088125  0.3631  ]
[ 3.1774 -2.6346  2.2381  1.1486]


In [ ]:
arr=np.random.randn(100)
arr

array([-0.12184735, -1.44026677, -0.64427408,  1.31633904, -0.18734521,
        0.19873609,  1.03438271,  0.32399322,  1.10602924,  1.93042853,
       -0.80711715, -0.44188687,  0.17703598, -1.46815143, -1.26107252,
       -0.20701469, -0.44955783,  0.77061172,  1.05096361,  0.33541193,
        0.23387385,  0.03179475,  1.01064036, -0.82810116, -0.17397814,
       -0.75818181, -1.46740541,  1.05886999, -0.10762441, -1.24592264,
       -1.03777556,  0.55947678,  1.00434145, -0.3511609 , -0.86342618,
       -0.25558577, -1.02323622, -0.46904866, -0.57745872,  0.61794034,
        0.44445055, -1.23879156,  0.56541877,  0.54745898,  1.63968012,
       -0.26116571, -0.07333788,  1.61123086,  2.040925  , -1.87629083,
        0.18679463,  1.50642748,  0.92910536, -0.08026447,  0.78816197,
       -1.24086895, -0.4216928 , -0.44291886, -0.3158335 ,  0.17030083,
       -0.3479657 , -0.63331908,  1.66354359, -0.06683816,  0.62581532,
       -1.72483329, -0.98685677, -0.28964216, -0.0169875 , -0.38

In [ ]:
(arr>0).sum() # sum เลขที่มีค่าบวก

45

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
result = np.where(arr <= 5, arr, 0) # np.where(เงื่อนไข, ตัวเป้าหมาย, ผิดเงื่อนไขจะเป็น)
print(result)

[1 2 3 4 5 0 0 0]


In [ ]:
arr1=np.array([[10,20],[30,40]])
arr2=np.array([[100,200],[300,400]])
new_arr=np.append(arr1,arr2,axis=0)
new_arr

array([[ 10,  20],
       [ 30,  40],
       [100, 200],
       [300, 400]])

In [ ]:
arr1=np.array([[10,20],[30,40]])
arr2=np.array([[100,200],[300,400]])
new_arr=np.append(arr1,arr2,axis=1)
new_arr

array([[ 10,  20, 100, 200],
       [ 30,  40, 300, 400]])