In [2]:
import numpy as np
np.random.seed(0)

x2 = np.random.randint(10, size=(3, 4))

In [ ]:
x2

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [ ]:
x2[:3, ::2]

array([[5, 3],
       [7, 3],
       [2, 7]])

In [ ]:
x2[:2, :3]

array([[5, 0, 3],
       [7, 9, 3]])

In [ ]:
x2[::-1,::-1]

array([[6, 7, 4, 2],
       [5, 3, 9, 7],
       [3, 3, 0, 5]])

In [ ]:
x2[:,0]

array([5, 7, 2])

In [ ]:
print(x2[0])

[5 0 3 3]


In [3]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [4]:
z = [99, 99, 99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [6]:
grid = np.array([[1, 2, 3],[4, 5, 6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [7]:
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [9]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [10]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [16]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [19]:
grid.transpose()

array([[9, 6],
       [8, 5],
       [7, 4]])

In [21]:
grid.sort()