Panutad Sirikul

650510714

Lab02

229323 Sec 002

# ให้นักศึกษาทำการเขียนโปรแกรมคำสั่ง เพื่อให้เกิดผลลัพธ์ตามที่แสดงใน output โดยสามารถเขียนคำสั่งมากกว่า 1 คำสั่ง

In [1]:
import numpy as np

## 1. สร้าง ndarray ชื่อ array_a จาก list ให้มีขนาด 2 มิติ



In [2]:
array_a = np.array([[1,2,3],[4,5,6]])
print(array_a)

[[1 2 3]
 [4 5 6]]


In [3]:
array_a = np.arange(1,7)
array_a = array_a.reshape(2,3)
print(array_a)

[[1 2 3]
 [4 5 6]]


In [4]:
from numpy import random
array_a = np.random.randint(1,7,60)
array_a = np.unique(array_a)
array_a = array_a.reshape(2,3)
print(array_a)

[[1 2 3]
 [4 5 6]]


## 2. สร้าง ndarray ชื่อ array_b โดยใช้ ฟังก์ชัน arange

In [5]:
array_b = np.arange(2,14,2)
array_b = array_b.reshape(3,2)
print(array_b)

[[ 2  4]
 [ 6  8]
 [10 12]]


## 3.ให้ทำการแสดงค่าจำนวนคอลัมน์ของ array_a และจำนวนแถวของ array_b

In [6]:
col_a = array_a.copy() # เพื่อไม่กระทบเจ้าของเดิม
col_a = col_a.shape[1]

row_b = array_b.copy()
row_b = row_b.shape[0]
print("column of array_a : ", col_a)
print("row of array_b : ", row_b)

column of array_a :  3
row of array_b :  3


## 4. ทำการคูณเมทริกซ์ array_a และ เมทริกซ์ array_b แล้วเก็บผลลัพธ์ไว้ที่เมทริกซ์ array_c

In [9]:
array_c = np.dot(array_a, array_b)
print(array_c)

[[ 44  56]
 [ 98 128]]


## 5.หาค่า determinant ของเมริกซ์ array_c

In [12]:
det_c = np.linalg.det(array_c)
print("Determinant of matrix C : ", det_c)

Determinant of matrix C :  143.99999999999937


## 6.หาค่า inverse ของเมริกซ์ array_c

In [15]:
inv_c = np.linalg.inv(array_c)
print("Inverse matrix c : ", inv_c)

Inverse matrix c :  [[ 0.88888889 -0.38888889]
 [-0.68055556  0.30555556]]


## 7. แสดงค่าของข้อมูลแถวสุดท้ายของ array_a โดยใช้คำสั่งในการหาตำแหน่ง (index) ของแถวสุดท้าย **ห้ามใช้การคีย์ระบุหมายเลขของแถวสุดท้ายเอง**

In [17]:
print(array_a[1, :])

[4 5 6]


In [18]:
print(array_a[:][1])

[4 5 6]


In [20]:
print(array_a[1][:])

[4 5 6]


## 8. แสดงค่า col สุดท้าย ของทุกแถวที่เป็นเลขคู่ของ array_b **ห้ามใช้การคีย์ระบุหมายเลขของคอลัมน์สุดท้าย**

In [23]:
print(array_b[::2, 1]) # ขยับ row ทีละ 2 (แถวที่ 0 และ 2) col ที่ 1

[ 4 12]


In [24]:
print(array_b[::2, -1])

[ 4 12]
