# NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Using NumPy

Once you've installed NumPy you can import it as a library:
https://numpy.org/doc/stable/index.html

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
my_list = [1,2,3]
print(my_list)
print(type(my_list))

[1, 2, 3]
<class 'list'>


In [13]:
np.array(my_list)  # create and print

array([1, 2, 3])

In [14]:
x = np.array(my_list)
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)
print(type(my_matrix))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
y = np.array(my_matrix)
print(y)
print(type(y))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### diag
Return a diagonal or construct a diagonal array

In [24]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [25]:
np.diag(np.array([1, 2, 3]))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [27]:
x = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(x)
print(np.diag(x))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


### linspace
Return evenly spaced numbers over a specified interval.

In [31]:
np.linspace(0,10,3) # สร้าง array ที่มีค่า 0-10 แล้วแบ่งเป็น 3 ส่วนเท่ากัน

array([ 0.,  5., 10.])

In [30]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [32]:
np.eye(4) # สร้างแนวแทยงเป็นหนึ่ง

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.identity(4) # ต่างจาก eye ที่ว่า eye สามารถสร้างแบบ แถวไม่เท่ากับหลักได้ แต่ identity แถวกับคอลัมน์ต้องเท่ากัน

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
# แทรก eye (จำนวนมิติหรือแถว [,จำนวนคอลัมน์] [,ตำแหน่งเริ่มแทยงมุม] [,ชนิดข้อมูล])
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [37]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

## Random

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [45]:
np.random.rand(2) # ขอ random มา 2 ตัว

array([0.98684766, 0.66820405])

In [44]:
# อีกวิธีหนึ่งของการใช้งาน
from numpy import random as rd
rd.rand(2) # ขอ random มา 2 ตัว

array([0.26379879, 0.37070022])

In [43]:
np.random.rand(5,5) # ได้ array 2D แบบ 5x5

array([[0.24333553, 0.81219837, 0.04196507, 0.41048891, 0.90645294],
       [0.88346121, 0.16654609, 0.30203627, 0.03926048, 0.05252909],
       [0.60372936, 0.50331039, 0.58933754, 0.03158277, 0.2989001 ],
       [0.93244729, 0.04702624, 0.61326505, 0.70550263, 0.00841507],
       [0.68673699, 0.46037037, 0.43535514, 0.7286576 , 0.46223212]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [48]:
np.random.randn(2) # เติม "n" มันจะสุ่มด้วย normal distribution

array([0.00107234, 0.93961924])

In [47]:
np.random.randn(5,5)

array([[ 0.03940956,  0.27564426,  0.15107089,  0.695323  , -1.18078724],
       [-0.08726442,  0.09983754,  2.61009288, -0.59044295, -1.24137641],
       [ 0.24164128, -0.25419731,  0.73388995, -0.35565929, -1.27384578],
       [-0.46945199,  0.07528908, -0.09892471, -0.05209712, -1.23622327],
       [-2.02841484, -0.06809171, -0.5779846 , -0.01476853, -0.0528114 ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [51]:
np.random.randint(1,100) # สุ่มมาเลขหนึ่งจาก 1-99

64

In [56]:
np.random.randint(100) # แบบนี้ก็ได้

35

In [52]:
np.random.randint(1,100,10)

array([ 2, 24, 45, 86,  9, 97,  4, 67, 66, 43])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [60]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10) # random มา 10 ตัว

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
ranarr

array([23, 48,  1,  0, 12,  4,  8,  6, 18,  3])

## Reshape
Returns an array containing the same data with a new shape.

In [63]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [64]:
ranarr

array([23, 48,  1,  0, 12,  4,  8,  6, 18,  3])

In [65]:
ranarr.max()

48

In [67]:
ranarr.argmax() # หาตำแหน่งของค่า max

1

In [68]:
ranarr.min()

0

In [69]:
ranarr.argmin() # ตำแหน่งที่ min อยู่

3

### sum, mean, std
These are used for computing summarize, mean and standard deviation

In [70]:
ranarr1 = np.random.randint(0,50,10)

In [71]:
ranarr1

array([32,  9, 27,  4, 13,  7, 25, 18, 25, 38])

In [72]:
ranarr1.sum()

198

In [73]:
ranarr1.mean()

19.8

In [74]:
ranarr1.std()

10.796295661012623

## Shape

Shape is an attribute that arrays have (not a method):

การเป็น method คือจะมี ( ) ต่อท้าย

In [78]:
# Vector
arr.shape  # array 1 มิติเรียกว่า vector

(25,)

In [79]:
# Notice the two sets of brackets
print(arr)
print("............")
print(arr.reshape(1,25)) # array 2 มิติเรียกว่า matrix

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
............
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]]


In [81]:
arr.reshape(1,25).shape # การถามว่า shape คืออะไร

(1, 25)

In [82]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [83]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [84]:
arr.dtype

dtype('int64')

## Set Operations

### unique

Select only one value, no duplicate data in same value

In [87]:
arr = np.array([2, 1, 2, 4, 5, 3, 2, 1, 4, 6])
np.unique(arr)  # คำตอบจะ sorted ด้วย

array([1, 2, 3, 4, 5, 6])

In [86]:
names = np.array(['Bob', 'Tom', 'Bill', 'Jane', 'Bob', 'Joe', 'Bob', 'Tom'])
np.unique(names)

array(['Bill', 'Bob', 'Jane', 'Joe', 'Tom'], dtype='<U4')

In [92]:
names = np.array(['Bob', 'Tom', 'Bill', 'Jane', 'Bob', 'Joe', 'Bob', 'Tom'])
sorted(set(names))  # สร้าง set (ตัดคำซ้ำออก) แล้ว sorted

['Bill', 'Bob', 'Jane', 'Joe', 'Tom']

### in1d(x, y)
Compute a boolean array indicating whether each element of x is contained in y

In [91]:
arr = np.array([2, 0, 2, 4, 5, 3, 2, 1, 4, 6])
np.in1d(arr, [0,1,5])  # สมาชิกแต่ละตัวอยู่ใน [0,1,5] หรือไม่

array([False,  True, False, False,  True, False, False,  True, False,
       False])

# Great Job!