# การใช้ numpy กับข้อมูลอาร์เรย์ (ndarray) ในมุมมอง matrix

In [ ]:
import numpy as np

## การสร้างอาร์เรย์จาก list, tuple หรือ range, arange

The function **range** returns a range object, while **arange** function returns a NumPy array.

In [ ]:
grid_1 = np.array(range(3, 7))
grid_2 = np.array([[1, 2], [3, 4]])
print(grid_1)
print("------------")
print(grid_2)

[3 4 5 6]
------------
[[1 2]
 [3 4]]


arange สามารถกำหนด start, stop, step ได้

In [ ]:
grid_3 = np.arange(2, 20, 2) # 2-19 step by 2
print(grid_3)

[ 2  4  6  8 10 12 14 16 18]


The function **linspace** returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number.

In [ ]:
#สร้างตัวเลข 5 ค่าที่อยู่ในช่วง [2, 3]
arr = np.linspace(2.0, 3.0, num=5)
print(arr)
arr = np.linspace(2, 3, 5)
print(arr)

[2.   2.25 2.5  2.75 3.  ]
[2.   2.25 2.5  2.75 3.  ]


In [ ]:
arr = np.linspace(2, 3, 5, retstep=True) # step ทีละเท่าไร
print(arr)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


In [ ]:
arr = np.linspace(2, 3, 4, retstep=True)
print(arr)

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)


## attribute ต่างๆ ที่สามารถใช้กับ ndarray



### shape, reshape, size, ndim

In [ ]:
print(grid_1)
print(grid_2)
print("----------")
print(grid_1.shape) #print(np.shape(grid_1))
print(np.shape(grid_2)) #print(grid_2.shape)
print("---size---")
print(grid_1.size)
print(np.size(grid_2)) # นับสมาชิก
print(grid_3)
print(np.size(grid_3)) # นับสมาชิก

[3 4 5 6]
[[1 2]
 [3 4]]
----------
(4,)
(2, 2)
---size---
4
4
[ 2  4  6  8 10 12 14 16 18]
9


In [ ]:
print(grid_3.shape)
#reshape เมทริกซ์แล้วแสดงผลแต่ไม่ได้แก้ไขตัวเมทริกซ์
grid_3.reshape((3,3))

(9,)


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
grid_3 # reshape ไม่มีผลกระทบ ได้ผลลัพธ์เดิม

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
grid_3.ndim

1

In [ ]:
grid_4 = grid_3.reshape((3,3))
grid_4.ndim #np.ndim(grid_4)

2

### matrix operation (use arithematic symbols)

In [ ]:
arr1 = np.arange(2, 6)
arr2 = np.arange(1, 5)

print("arr 1 : ", arr1)
print("arr 2 : ", arr2)
arr_addition = arr1+arr2
print("addition",arr_addition)
arr_minus = arr1-arr2
print("minus",arr_minus)
arr_multiply = arr1*arr2
print("multiply",arr_multiply)
arr_division = arr1/arr2
print("arr_division",arr_division)
arr_reverse = 1/arr1
print("arr_reverse",arr_reverse)

arr 1 :  [2 3 4 5]
arr 2 :  [1 2 3 4]
addition [3 5 7 9]
minus [1 1 1 1]
multiply [ 2  6 12 20]
arr_division [2.         1.5        1.33333333 1.25      ]
arr_reverse [0.5        0.33333333 0.25       0.2       ]


### method add, subtract, multiply, power, maximum, mod

In [ ]:
arr1 = np.arange(2, 6)
arr2 = np.arange(1, 5)

print("arr 1 : ", arr1)
print("arr 2 : ", arr2)
print("addition : ", np.add(arr1, arr2))
print("minus : ", np.subtract(arr1, arr2))
print("multiply : ", np.multiply(arr1, arr2))
print("power : ", np.power(arr1, arr2))
print("power by 2 : ", np.power(arr1, 2))
print("maximum between 2 matrices : ", np.maximum(arr1, arr2))
print("modulo between 2 matrices : ", np.mod(arr1, arr2))

arr 1 :  [2 3 4 5]
arr 2 :  [1 2 3 4]
addition :  [3 5 7 9]
minus :  [1 1 1 1]
multiply :  [ 2  6 12 20]
power :  [  2   9  64 625]
power by 2 :  [ 4  9 16 25]
maximum between 2 matrices :  [2 3 4 5]
modulo between 2 matrices :  [0 1 1 1]


### ceil, floor, exp, sqrt

In [ ]:
f_arr =  np.array([2.2, 3.4, 4.6])
print(f_arr)
print("ceil : ", np.ceil(f_arr))
print("floor : ", np.floor(f_arr))
print("exponential of all elements : ", np.exp(f_arr))
print("square root of all elements : ", np.sqrt(f_arr))

[2.2 3.4 4.6]
ceil :  [3. 4. 5.]
floor :  [2. 3. 4.]
exponential of all elements :  [ 9.0250135  29.96410005 99.48431564]
square root of all elements :  [1.4832397  1.84390889 2.14476106]


In [ ]:
arry = np.random.randn(3,4)
print(arry)
print("mean =",arry.mean()) #print(np.mean(arry))
print("sum =",arry.sum())
print("std =",arry.std())

[[ 0.37816049  1.15837015 -0.58659226 -1.72559121]
 [-0.97414742  0.19254352 -0.60439791  0.85353959]
 [-0.52746033 -0.65143603 -1.23489881  0.2775121 ]]
mean = -0.2870331763279929
sum = -3.444398115935915
std = 0.8267587271984814


In [ ]:
arry = np.array([[1,2],[3,4],[5,6]])
print("array =",arry)
print("cumsum : ",arry.cumsum())
print("cumsum axis=1 : " )
print(arry.cumsum(axis=1)) # แนว
print("cumprod axis=0")
print(arry.cumprod(axis=0))

array = [[1 2]
 [3 4]
 [5 6]]
cumsum :  [ 1  3  6 10 15 21]
cumsum axis=1 : 
[[ 1  3]
 [ 3  7]
 [ 5 11]]
cumprod axis=0
[[ 1  2]
 [ 3  8]
 [15 48]]


### การเปลี่ยนชนิดข้อมูลบนอาร์เรย์ด้วย method astype

In [ ]:
arr = np.array([2.8, 4.6, 7, 10.3, 18])
print(arr)
print(arr.astype(int))
print(arr.astype(str))

[ 2.8  4.6  7.  10.3 18. ]
[ 2  4  7 10 18]
['2.8' '4.6' '7.0' '10.3' '18.0']


## การอ้างอิงข้อมูล

### การอ้างอิงถึงข้อมูลในอาร์เรย์ แบบระบุ index

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr[1][2])
print(arr[0][1])

[[1 2 3]
 [4 5 6]]
6
2


### การอ้างอิงถึงสมาชิกทีละหลายตัว โดยใช้ :

In [ ]:
print(arr)
print("............")
print(arr[1][:]) #แถวที่ 1
print(arr[1,:])  #แถวที่ 1
print(arr[:][1]) #แถวที่ 1
print(arr[:, 1])
print(arr[::-1, ::-1])

[[1 2 3]
 [4 5 6]]
............
[4 5 6]
[4 5 6]
[4 5 6]
[2 5]
[[6 5 4]
 [3 2 1]]


In [ ]:
#2-dimensional array
n_arr = np.array([[2, 4, 6, 8], [3, 5, 7, 8], [10, 11, 12, 13]])
print(n_arr)

[[ 2  4  6  8]
 [ 3  5  7  8]
 [10 11 12 13]]


In [ ]:
print(n_arr[1:2, 2:3]) #แถวที่ 1 คอลัมน์ที่ 2
print(n_arr[::2, 2]) #ขยับ row ทีละ 2 col ที่ 2
print(n_arr[0, 1:3])  #แถวที่ 0 คอลัมน์ 1 ถึง 2

[[7]]
[ 6 12]
[4 6]


### การแก้ไขค่าสมาชิกหลายตัวในแถวหรือหลักเดียวกัน (broadcast)

In [ ]:
arr_n = np.ones((3, 3))
print(arr_n)
arr_n[1, :] = 4  #เปลี่ยนแถวที่ 1 ทุกคอลัมน์ให้เป็นเลข 4
print("-----------")
print(arr_n)
arr_n[:, 2] = 5  #เปลี่ยน ทุกแถวที่อยู่ใน คอลัมน์ที่ 2 ให้เป็นเลข 5
print("-----------")
print(arr_n)
arr_n[:, :] = np.array([7, 8, 9])  # Change every row and col to 7,8,9
print("-----------")
print(arr_n)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----------
[[1. 1. 1.]
 [4. 4. 4.]
 [1. 1. 1.]]
-----------
[[1. 1. 5.]
 [4. 4. 5.]
 [1. 1. 5.]]
-----------
[[7. 8. 9.]
 [7. 8. 9.]
 [7. 8. 9.]]


## การ copy ข้อมูล ndarray

### การใช้เครื่องหมาย = ในการ copy ข้อมูล

เป็นการให้ตัวแปรใหม่แทน ออบเจ็กต์ array ตัวเดียวกัน หากมีการเปลี่ยนแปลงค่าภายในของออบเจ็กต์ ตัวหนึ่ง ข้อมูลอีกออบเจ็กต์ก็จะมีการเปลี่ยนแปลงตามไปด้วย

In [ ]:
m_arr = np.array([2, 3, 5, 7, 8])
cm_arr = m_arr  # อยู่ที่เดียวกัน กระทบเจ้าของเดิมด้วย!?
print(m_arr)
print("-----------")
print(cm_arr)
cm_arr[3] = 25
print("-----------")
print(cm_arr)
print("-----------")
print(m_arr)

[2 3 5 7 8]
-----------
[2 3 5 7 8]
-----------
[ 2  3  5 25  8]
-----------
[ 2  3  5 25  8]


### การใช้ method copy() ในการคัดลอกข้อมูล

In [ ]:
m_arr = np.array([2, 3, 5, 7, 8])
cm_arr = m_arr.copy() # ไม่กระทบเจ้าของแล้ว!!
print(m_arr)
print("-----------")
print(cm_arr)
cm_arr[3] = 25
print("-----------")
print(cm_arr)
print("-----------")
print(m_arr)

[2 3 5 7 8]
-----------
[2 3 5 7 8]
-----------
[ 2  3  5 25  8]
-----------
[2 3 5 7 8]


In [ ]:
cm_arr2 = m_arr[2:].copy()
print(cm_arr2)

[5 7 8]
